### ISSUE TITLE
Build CoreUI in Laravel 5.7 with javascript error

### ISSUE THREAD

**Issue by htn** [coreui/coreui-free-vue-admin-template#129]
Hi all, how to fix my problem below?
I copy src folder CoreUI to E:/xampp/htdocs/laravel56/resources/assets/js and rename to admin, config package.json....
I run "npm run dev" error in file:
`E:/xampp/htdocs/laravel56/resources/assets/js/admin/router/index.js `
Error in row:
`const DefaultContainer = () => import('@/containers/DefaultContainer')`
Error:
```
ERROR in ./resources/assets/js/admin/router/index.js
Module build failed: SyntaxError: E:/xampp/htdocs/laravel56/resources/assets/js/admin/router/index.js: Unexpected token (5:31)

```

**Comment by eduditurbide** [comment]
@mrholek  You have to make a small guide to integrate this awesome template with laravel!
Please sir!

**Comment by eleazarpuntonet** [comment]
There is no documentation to implement this template

**Comment by woothu** [comment]
Hello! 

We would recommend have separated laravel and coreui projects and use laravel only as a RESTful API, because in SPA frontend approach you can't really utilize laravel blade templates.

This solution also brings more flexibility and is making frontend of the app reusable for other backend solutions.
