### ISSUE TITLE
Add classes to the body is not possible

### ISSUE THREAD

**Issue by mjsorribas** [coreui/coreui-free-vue-admin-template#169]
Operative System: Linux Manjaro
Browser: Firefox & Chrome

What are try to do:
Add one class to the **body** element to control the **footer** visibility with "footer-fixed" class.

What is the problem:
The class dissapear from the body class attribute when the page is loading.

When this not happend:
When the class name is write like this ".footer-fixed", but does not work propertly with the dot .

**Comment by mjsorribas** [comment]
I've was fix the problem using on the footer component the word "fixed".
Example: 
  <TheFooter fixed>
This change add to the body the class directly.

But I don't know why I can't add classes to the body properly in the case If I want add another class for example.

**Comment by woothu** [comment]
Thank you for reporting this issue. 

In version 3 (coming soon) components state will not be determined by body classes (which are toggled what may cause your issue), but internal component state, so this issue will be resolved.

**Comment by greeven** [comment]
Hi @mjsorribas , your example of the fix doesn't show anymore. Could you provide what you found?

**Comment by greeven** [comment]
Never mind. Found it. So adding ".footer-fixed" in the body class found in "public/index.html" keeps the footer-fixed class but doesn't help because ".footer-fixed" has no style set.

Adding "fixed" to "src/containers/DefaultFooter.vue" works.

Old: `<TheFooter>`
New: `<TheFooter fixed>`

I'm currently using `"@coreui/coreui": "^2.1.12",`.
