### ISSUE TITLE
Object doesn't support property or method 'assign' on IE11

### ISSUE THREAD

**Issue by daynt** [coreui/coreui-free-vue-admin-template#187]
I tried to use CoreUI-Vue PRO 3.0 beta-1 with Internet Explorer 11 but the page doesn't show up.

Even your demo page doesn't show up.

The web console prints out "SCRIPT438: Object doesn't support property or method 'assign'"
`
![putty_xhkBQDgJVP](https://user-images.githubusercontent.com/3105208/72082289-3c207c80-3300-11ea-84fd-4c5fb3716059.png)

**Comment by woothu** [comment]
Hi! thank you for reporting this issue! It was really helpful because ie11 was working before, and I didn't check it after some breaking-ie11 dependencies have been introduced.

The next release will be fixed. For a quick fix:

In package.json
```
    "@coreui/vue": "coreui/coreui-vue#3.0.0-beta.7",
    "@coreui/vue-chartjs": "coreui/coreui-vue#1.0.3",
```
then run npm i

in babel.config.js
```
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        useBuiltIns: 'entry',
        corejs: 3
      }
    ]
  ]
}

```

in vue.config.js
```
module.exports = {
  lintOnSave: false,
  runtimeCompiler: true,
  configureWebpack: {
    //Necessary to run npm link https://webpack.js.org/configuration/resolve/#resolve-symlinks
    resolve: {
       symlinks: false
    }
  },
  transpileDependencies: [
    '@coreui/utils'
  ]
}

```
in main.js add
```
import 'core-js/stable'
```
