### ISSUE TITLE
question: how to dynamically show/hide items in Sidebar

### ISSUE THREAD

**Issue by fancydev18** [coreui/coreui-free-vue-admin-template#207]
Hi,

```
When asking general "how to" questions:
- Please do not open an issue here
```
Where should one ask instead?

Question is, how to make each Sidebar item here
https://github.com/coreui/coreui-free-vue-admin-template/blob/0d2b619677ba170898ec19ae9ad0a99db22b5d51/src/containers/_nav.js

be shown only if a condition is met, depending on Vue store?

Use case: show an item only if user permissions allow access to that item.

eg
```
 {
        _name: 'CSidebarNavItem',
        name: 'Colors',
        to: '/theme/colors',
        icon: 'cil-drop',
        showIf: "store.user.permissions.includes('Colors')"
      },
```
For ```store``` to work, how should it be declared in this file?

Thanks!

**Comment by woothu** [comment]
> Where should one ask instead?

Documentation is answering 'how-to' questions. If documentation is not sufficient, the issue is about a lack of documentation.

CRenderFunction docs:
https://coreui.io/vue/docs/components/render-function.html

Backend integration docs:
https://coreui.io/vue/docs/introduction/template.html#backend-integration

Generally in your case, you have access to store only in Vue components. So the best way is to compute your items as shown in the 'backend integration' section based on your store state.
